name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xrdp and configure for root
        run: |
          # Install xrdp
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 

          sudo dpkg -i cloudflared.deb && 

          sudo cloudflared service install eyJhIjoiZDY3NTQzYWUxNGFlZTkwMmRhZmNjNGQyNTFhNzEzY2QiLCJ0IjoiYTM4NGE2YzUtODNlNy00YjFhLTg2NDMtMzc4NWZiYWFlMGQxIiwicyI6Ik5qazFaamMzTmprdE1UQXpOeTAwWVdNeUxXSmpPV0l0TVRGaU9EQXhPVGxtTVdKaiJ9



          # Set up the password for the root user to "admin"
          echo 'root:admin' | sudo chpasswd

      - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
