name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xrdp and configure for root
        run: |
          # Install xrd
          sudo apt update
          sudo apt install sudo curl wget nano screen git -y
          sudo apt install neofetch -y
          sudo apt upgrade -y
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 

          sudo dpkg -i cloudflared.deb && 

          sudo cloudflared service install eyJhIjoiZDY3NTQzYWUxNGFlZTkwMmRhZmNjNGQyNTFhNzEzY2QiLCJ0IjoiYTM4NGE2YzUtODNlNy00YjFhLTg2NDMtMzc4NWZiYWFlMGQxIiwicyI6Ik5qazFaamMzTmprdE1UQXpOeTAwWVdNeUxXSmpPV0l0TVRGaU9EQXhPVGxtTVdKaiJ9

          

      - name: Keep Alive
        run: |
          # Add a long-running command to keep the workflow alive
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Sleep for 1 hour
          done 
