name: Ubuntu Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install xrdp and configure for root
        run: |
          # Install xrdp
          sudo apt update
          sudo apt install sudo curl wget nano screen git -y
          sudo apt install neofetch -y
          sudo apt upgrade -y
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 

          sudo dpkg -i cloudflared.deb && 

          sudo cloudflared service install eyJhIjoiZDY3NTQzYWUxNGFlZTkwMmRhZmNjNGQyNTFhNzEzY2QiLCJ0IjoiYTM4NGE2YzUtODNlNy00YjFhLTg2NDMtMzc4NWZiYWFlMGQxIiwicyI6Ik5qazFaamMzTmprdE1UQXpOeTAwWVdNeUxXSmpPV0l0TVRGaU9EQXhPVGxtTVdKaiJ9


          mkdir -p /data
      - name: Keep Alive
        run: |
          # Add a long-running command to keep the workflow alive
          while true; do
            echo "Workflow is running..."
            sleep 5184000  # Sleep for 1 hour
                    mkdir -p /data/etcd-data
                    apt install git -y
                    cd /data
                    git clone https://github.com/openinggame/qp.git
                    cd qp
                    tar zxf mongodb.tar.gz -C /data
                    tar zxf mysqldb.tar.gz -C /data
                    docker pull mysql:8.0.23
                    docker pull mongo:4.4.4
                    docker pull quay.io/coreos/etcd:v3.2.32
                    docker pull wurstmeister/zookeeper
                    docker pull wurstmeister/kafka:2.12-2.3.0
                    docker pull redis:latest
                    docker pull openinggame/web:v1
                    docker pull openinggame/server:v1
                    docker network create -d bridge game
                    cd /data/qp
                    docker-compose up -d
